DCMS.Web/Controllers/Sales/ReturnReservationBillController.cs
using DCMS.Core;
using DCMS.Core.Caching;
using DCMS.Core.Domain.Configuration;
using DCMS.Core.Domain.Products;
using DCMS.Core.Domain.Sales;
using DCMS.Core.Domain.Terminals;
using DCMS.Core.Domain.Users;
using DCMS.Core.Domain.WareHouses;
using DCMS.Services.Common;
using DCMS.Services.Configuration;
using DCMS.Services.ExportImport;
using DCMS.Services.Logging;
using DCMS.Services.Messages;
using DCMS.Services.Products;
using DCMS.Services.Purchases;
using DCMS.Services.Sales;
using DCMS.Services.Settings;
using DCMS.Services.Terminals;
using DCMS.Services.Users;
using DCMS.Services.WareHouses;
using DCMS.ViewModel.Models.Sales;
using DCMS.Web.Framework.Mvc.Filters;
using DCMS.Web.Infrastructure.Mapper.Extensions;
using DCMS.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Task = System.Threading.Tasks.Task;

namespace DCMS.Web.Controllers
{
    /// <summary>
    /// 退货订单
    /// </summary>
    public class ReturnReservationBillController : BasePublicController
    {
        private readonly IPrintTemplateService _printTemplateService;
        private readonly IUserActivityService _userActivityService;
        private readonly IReturnReservationBillService _returnReservationBillService;
        private readonly IReturnBillService _returnBillService;
        private readonly IDistrictService _districtService;
        private readonly IWareHouseService _wareHouseService;
        private readonly IProductService _productService;
        private readonly ISettingService _settingService;
        private readonly ISpecificationAttributeService _specificationAttributeService;
        private readonly IProductTierPricePlanService _productTierPricePlanService;
        private readonly IBranchService _branchService;
        private readonly IUserService _userService;
        private readonly ITerminalService _terminalService;
        private readonly IAccountingService _accountingService;
        private readonly IMediaService _mediaService;
        private readonly IRedLocker _locker;
        private readonly IExportManager _exportManager;
        private readonly IPurchaseBillService _purchaseBillService;

        public ReturnReservationBillController(
            IWorkContext workContext,
            IStoreContext storeContext,
            ILogger loggerService,
            IPrintTemplateService printTemplateService,
            IUserActivityService userActivityService,
            IReturnReservationBillService returnReservationBillService,
            IReturnBillService returnBillService,
            IDistrictService districtService,
            IWareHouseService wareHouseService,
            IProductService productService,
            ISettingService settingService,
            ISpecificationAttributeService specificationAttributeService,
            IProductTierPricePlanService productTierPricePlanService,
            IBranchService branchService,
            IUserService userService,
            ITerminalService terminalService,
            IAccountingService accountingService,
            IMediaService mediaService,
            INotificationService notificationService,
            IRedLocker locker,
            IExportManager exportManager,
            IPurchaseBillService purchaseBillService
            ) : base(workContext, loggerService, storeContext, notificationService)
        {
            _printTemplateService = printTemplateService;
            _userActivityService = userActivityService;
            _returnReservationBillService = returnReservationBillService;
            _returnBillService = returnBillService;
            _districtService = districtService;
            _wareHouseService = wareHouseService;
            _productService = productService;
            _specificationAttributeService = specificationAttributeService;
            _productTierPricePlanService = productTierPricePlanService;
            _settingService = settingService;
            _branchService = branchService;
            _userService = userService;
            _terminalService = terminalService;
            _accountingService = accountingService;
            _mediaService = mediaService;
            _locker = locker;
            _exportManager = exportManager;
            _purchaseBillService = purchaseBillService;
        }

        public IActionResult Index()
        {
            return RedirectToAction("List");
        }

        [AuthCode((int)AccessGranularityEnum.ReturnOrderView)]
        public IActionResult List(int? terminalId, string terminalName, int? businessUserId, int? deliveryUserId, int? wareHouseId = null, int? districtId = null, string billNumber = "", string remark = "", DateTime? startTime = null, DateTime? endTime = null, bool? auditedStatus = null, bool? sortByAuditedTime = null, bool? showReverse = null, bool? showReturn = null, bool? alreadyChange = null, int pagenumber = 0)
        {
            var companySetting = _settingService.LoadSetting<CompanySetting>(curStore.Id);
            var model = new ReturnReservationBillListModel();

            if (pagenumber > 0)
            {
                pagenumber -= 1;
            }

            #region 绑定数据源

            model = PrepareReturnReservationBillListModel(model);

            model.TerminalId = terminalId ?? null;
            model.TerminalName = terminalName;
            model.BusinessUserId = businessUserId ?? null;
            model.DeliveryUserId = deliveryUserId ?? null;
            model.BillNumber = billNumber;
            model.WareHouseId = wareHouseId ?? null;
            model.DistrictId = districtId ?? null;
            model.Remark = remark;
            model.StartTime = startTime ?? DateTime.Parse(DateTime.Now.ToString("yyyy-MM-01"));
            model.EndTime = endTime ?? DateTime.Now.AddDays(1);

            model.AuditedStatus = auditedStatus;
            model.SortByAuditedTime = sortByAuditedTime;
            model.ShowReverse = showReverse;
            model.ShowReturn = showReturn;
            model.AlreadyChange = alreadyChange;
            #endregion

            var returns = _returnReservationBillService.GetReturnReservationBillList(curStore?.Id ?? 0,
                 curUser.Id,
                terminalId,
                terminalName,
                businessUserId,
                deliveryUserId,
                billNumber,
                wareHouseId,
                remark,
                //startTime, //?? DateTime.Parse(DateTime.Now.ToString("yyyy-MM-dd")),
                //endTime, //?? DateTime.Now.AddDays(1),
                model.StartTime,
                model.EndTime,
                districtId,
                auditedStatus,
                sortByAuditedTime,
                showReverse,
                alreadyChange,
                false,//未删除单据
                pagenumber,
                pageSize: 30);

            //默认账户
            var defaultAcc = _accountingService.GetDefaultAccounting(curStore?.Id ?? 0, BillTypeEnum.ReturnReservationBill);
            model.DynamicColumns = defaultAcc?.Item4?.OrderBy(s => s.Key).Select(s => s.Value).ToList();

            model.PagingFilteringContext.LoadPagedList(returns);

            #region 查询需要关联其他表的数据

            var allUsers = _userService.GetUsersDictsByIds(curStore.Id, returns.Select(b => b.BusinessUserId).Distinct().ToArray());
            var allTerminal = _terminalService.GetTerminalsByIds(curStore.Id, returns.Select(b => b.TerminalId).Distinct().ToArray());
            //var allWareHouses = _wareHouseService.GetWareHouseByIds(curStore.Id, returns.Select(b => b.WareHouseId).Distinct().ToArray());
            #endregion

            model.Lists = returns.Select(s =>
            {
                var m = s.ToModel<ReturnReservationBillModel>();


                //业务员名称
                m.BusinessUserName = allUsers.Where(aw => aw.Key == m.BusinessUserId).Select(aw => aw.Value).FirstOrDefault();
                //送货员名称
                m.DeliveryUserName = allUsers.Where(aw => aw.Key == m.DeliveryUserId).Select(aw => aw.Value).FirstOrDefault();

                //客户名称
                var terminal = allTerminal.Where(at => at.Id == m.TerminalId).FirstOrDefault();
                m.TerminalName = terminal?.Name;
                m.TerminalPointCode = terminal?.Code;

                //仓库名称
                var warehouse = model.WareHouses.Where(s => s.Value == m.WareHouseId.ToString()).FirstOrDefault();
                m.WareHouseName = warehouse?.Text;

                //应收金额	
                m.ReceivableAmount = (s.ReceivableAmount == 0) ? ((s.OweCash != 0) ? s.OweCash : s.ReturnReservationBillAccountings.Sum(sa => sa.CollectionAmount)) : s.ReceivableAmount;

                //收款账户
                m.ReturnReservationBillAccountings = defaultAcc?.Item4?.OrderBy(sb => sb.Key).Select(sb =>
                {
                    var acc = s.ReturnReservationBillAccountings.Where(a => a?.AccountingOption?.ParentId == sb.Key).FirstOrDefault();
                    return new ReturnReservationBillAccountingModel()
                    {
                        AccountingOptionId = acc?.AccountingOptionId ?? 0,
                        CollectionAmount = acc?.CollectionAmount ?? 0
                    };
                }).ToList();


                //查询退货订单 关联的退货单
                ReturnBill returnBill = _returnBillService.GetReturnBillByReturnReservationBillId(curStore.Id, m.Id);
                if (returnBill != null)
                {
                    m.ReturnBillId = returnBill.Id;
                    m.ReturnBillNumber = returnBill.BillNumber;
                }

                return m;
            }).ToList();

            return View(model);
        }

        /// <summary>
        /// 获取退货订单列表
        /// </summary>
        /// <param name="terminalId">客户</param>
        /// <param name="businessUserId">业务员</param>

DCMS.Web/Views/ReturnReservationBill/Create.cshtml
@using DCMS.Web.Framework.UI;
@using DCMS.Web.Framework;
@using DCMS.Core.Domain.Common;
@using DCMS.ViewModel.Models.Sales;

@model ReturnReservationBillModel

<section id="content_wrapper">

    <!-- Start: Topbar-Dropdown -->
    <div id="topbar-dropmenu">
        <div id="topbar-dropmenu">
            @await Html.PartialAsync("_ToolBox")
        </div>
    </div>
    <!-- End: Topbar-Dropdown -->
    <!-- Start: Topbar -->
    <header id="topbar">
        <div class="topbar-left">
            <ol class="breadcrumb">
                <li class="crumb-active">
                    <a href="@Url.RouteUrl("HomePage")">首页</a>
                </li>
                <li class="crumb-icon">
                    <a href="dashboard.html">
                        <span class="glyphicon glyphicon-home"></span>
                    </a>
                </li>
                <li class="crumb-link">
                    <a href="#">销售</a>
                </li>
                <li class="crumb-trail">退货订单</li>
            </ol>
        </div>
        <div class="topbar-right">
            <div class="ml15 ib va-m" id="toggle_sidemenu_r">
                <a href="#" class="pl5">
                    <i class="fa fa-sign-in fs22 text-primary"></i>
                    <span class="badge badge-hero badge-danger">3</span>
                </a>
            </div>
        </div>
    </header>
    <!-- End: Topbar -->
    <!-- Begin: Content -->
    <section id="content" class="formSection">
        <div class="row">
            <div class="col-md-12">

                <form asp-action="Create" asp-controller="ReturnReservationBill" asp-route-returnurl="@Context.Request.Query["ReturnUrl"]" method="post" class="form-horizontal" id="ReturnReservationBillForm">

                    <div class="panel">
                        <div class="panel-heading">
                            <div class="panel-title">
                                <span class="glyphicon glyphicon-tasks"></span> 创建退货订单
                            </div>
                        </div>
                        <div class="panel-body p10 pt10">
                            <div class="tab-block">
                                <ul class="nav nav-tabs tabs-bg">
                                    <li class="active">
                                        <a href="#tab10_1" data-toggle="tab" aria-expanded="true"><i class="fa fa-align-justify text-purple"></i> 单据信息</a>
                                    </li>
                                </ul>
                                <div class="tab-content">
                                    <div id="tab10_1" class="tab-pane active">
                                        @await Html.PartialAsync("_CreateOrUpdate", Model)
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="panel-footer">
                            <div class="form-group mbn">
                                <div class="col-lg-12">
                                    <button id="FormSubmit" type="button" class="btn btn-primary ladda-button" data-style="zoom-out" value="保存" @(Model.AuditedStatus ? "disabled" : "")><i class="fa fa-floppy-o mr5"></i>保存</button>
                                    <button id="FormSubmitContinue" type="button" class="btn btn-success ladda-button" data-style="zoom-out" name="save-continue" value="保存并继续" @(Model.AuditedStatus ? "disabled" : "")><i class="fa fa-clipboard mr5"></i>保存并继续</button>
                                    <button id="btn_auditing" type="button" class="btn btn-info ladda-button" data-style="zoom-out" disabled><span class="glyphicon glyphicon-check mr5" aria-hidden="true"></span>审核</button>
                                    <button id="btn_red" type="button" class="btn btn-danger ladda-button" data-style="zoom-out" @((Model.AuditedStatus && !Model.ReversedStatus) ? "" : "disabled")><span class="glyphicon glyphicon-transfer mr5" aria-hidden="true"></span>红冲</button>
                                    <button id="btn_print" type="button" class="btn btn-alert ladda-button" data-style="zoom-out" value="打印" @((Model.Id > 0) ? "" : "disabled")>
                                        <i class="fa fa-floppy-o mr5"></i>打印
                                    </button>
                                    <a class="btn btn-warning" href="@Context.Request.Query["returnURL"]"><i class="fa fa-undo mr5"></i> 返回</a>

                                </div>


                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
    <!-- End: Content -->
</section>



@await Html.PartialAsync("_Windows", Model)

@{
//Html.AddCssFileParts(ResourceLocation.Head, "~/assets/skin/default_skin/css/theme.css");
//Html.AddCssFileParts(ResourceLocation.Head, "~/Scripts/Toastr/toastr.css");
//Html.AddCssFileParts(ResourceLocation.Head, "~/Scripts/Tables/bootstrap-table.css");

//Html.AddCssFileParts(ResourceLocation.Head, "~/vendor/plugins/datepicker/css/bootstrap-datetimepicker.css");
//Html.AddCssFileParts(ResourceLocation.Head, "~/vendor/plugins/daterange/daterangepicker.css");
//Html.AddCssFileParts(ResourceLocation.Head, "~/vendor/plugins/tagmanager/tagmanager.css");

//Html.AddCssFileParts(ResourceLocation.Head, "~/vendor/plugins/fancytree/skin-win8/ui.fancytree.min.css");
//Html.AddCssFileParts(ResourceLocation.Head, "~/Content/zTree.theme.metro.min.css");

//Html.AddCssFileParts(ResourceLocation.Head, "~/vendor/plugins/spin/spin.css");
//Html.AddCssFileParts(ResourceLocation.Head, "~/vendor/plugins/ladda/ladda.min.css");
}

@section NewDefinFrameWorkScripts
                {
    @{
        Html.AddScriptParts(ResourceLocation.Footer, "~/vendor/jquery/jquery-1.11.1.min.js", order: 999);
        Html.AddScriptParts(ResourceLocation.Footer, "~/vendor/jquery/jquery_ui/jquery-ui.min.js", order: 999);
        Html.AddScriptParts(ResourceLocation.Footer, "~/assets/js/bootstrap/bootstrap.min.js", order: 999);
    }
}

@section CurPageScripts
{
    @{

//Html.AddScriptParts(ResourceLocation.Footer, "~/assets/js/utility/jquery.sparkline.min.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/Scripts/jquery.validate.min.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/Scripts/jquery.validate.unobtrusive.js");
////Html.AddScriptParts(ResourceLocation.Footer, "~/Scripts/Tables/jquery.treegrid.min.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/Scripts/jquery-ui-1.10.4.custom.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/Scripts/jquery.PrintArea.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/Scripts/Tables/bootstrap-table.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/Scripts/Tables/locale/bootstrap-table-zh-CN.min.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/Scripts/Tables/bootstrap-table-treeview.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/Scripts/globalize.min.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/Scripts/moment.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/Scripts/moment-with-locales.js");
////Html.AddScriptParts(ResourceLocation.Footer, "~/vendor/plugins/daterange/daterangepicker.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/vendor/plugins/datepicker/js/bootstrap-datetimepicker.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/vendor/plugins/jquerymask/jquery.maskedinput.min.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/vendor/plugins/tagmanager/tagmanager.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/vendor/plugins/fancytree/jquery.fancytree-all.min.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/Scripts/jquery.ztree.all-3.5.min.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/assets/js/bootstrap/holder.min.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/Scripts/Toastr/Toastr.min.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/Scripts/Custom/Common.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/vendor/plugins/spin/spin.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/vendor/plugins/ladda/ladda.min.js");

    }
    @await Html.PartialAsync("_Scripts", Model)
}

DCMS.Web/Views/ReturnReservationBill/Edit.cshtml
@using DCMS.Web.Framework.UI;
@using DCMS.Web.Framework;
@using DCMS.Core.Domain.Common;
@using DCMS.ViewModel.Models.Sales;
@using DCMS.Services.Sales;
@using DCMS.Core.Infrastructure;

@model ReturnReservationBillModel

<section id="content_wrapper">

    <!-- Start: Topbar-Dropdown -->
    <div id="topbar-dropmenu">
        <div id="topbar-dropmenu">
            @await Html.PartialAsync("_ToolBox")
        </div>
    </div>
    <!-- End: Topbar-Dropdown -->
    <!-- Start: Topbar -->
    <header id="topbar">
        <div class="topbar-left">
            <ol class="breadcrumb">
                <li class="crumb-active">
                    <a href="@Url.RouteUrl("HomePage")">首页</a>
                </li>
                <li class="crumb-icon">
                    <a href="dashboard.html">
                        <span class="glyphicon glyphicon-home"></span>
                    </a>
                </li>
                <li class="crumb-link">
                    <a href="#">销售</a>
                </li>
                <li class="crumb-trail">退货订单</li>
            </ol>
        </div>
        <div class="topbar-right">
            <div class="ml15 ib va-m" id="toggle_sidemenu_r">
                <a href="#" class="pl5">
                    <i class="fa fa-sign-in fs22 text-primary"></i>
                    <span class="badge badge-hero badge-danger">3</span>
                </a>
            </div>
        </div>
    </header>
    <!-- End: Topbar -->
    <!-- Begin: Content -->
    <section id="content" class="formSection">

        <div class="row">
            <div class="col-md-12">

                <form asp-action="Edit" asp-controller="ReturnReservationBill" asp-route-returnurl="@Context.Request.Query["ReturnUrl"]" method="post" class="form-horizontal" id="ReturnReservationBillForm">

                    <div class="panel">
                        <div class="panel-heading">
                            <div class="panel-title">
                                <span class="glyphicon glyphicon-tasks"></span> 编辑退货订单
                            </div>
                        </div>
                        <div class="panel-body p10 pt10">
                            <div class="tab-block">
                                <ul class="nav nav-tabs tabs-bg" id="ReturnReservationBillFormTab">
                                    <li class="active">
                                        <a href="#tab10_1" data-toggle="tab" data-id="0" aria-expanded="true"><i class="fa fa-align-justify text-purple"></i> 单据信息</a>
                                    </li>
                                </ul>
                                <div class="tab-content">
                                    <div id="tab10_1" class="tab-pane active">
                                        @await Html.PartialAsync("_CreateOrUpdate", Model)
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="panel-footer">
                            <div class="form-group mbn">
                                <div class="col-lg-12">
                                    <button id="FormSubmit" type="button" class="btn btn-primary ladda-button" data-style="zoom-out" value="保存" @(Model.AuditedStatus ? "disabled" : "")><i class="fa fa-floppy-o mr5"></i>保存</button>
                                    <button id="FormSubmitContinue" type="button" class="btn btn-success ladda-button" data-style="zoom-out" name="save-continue" value="保存并编辑" @(Model.AuditedStatus ? "disabled" : "")><i class="fa fa-clipboard mr5"></i>保存并编辑</button>
                                    <button id="btn_auditing" type="button" class="btn btn-info ladda-button" data-style="zoom-out" @(Model.AuditedStatus ? "disabled" : "")><span class="glyphicon glyphicon-check mr5" aria-hidden="true"></span>审核</button>
                                    <button id="btn_red" type="button" class="btn btn-danger ladda-button" data-style="zoom-out" @((Model.AuditedStatus && !Model.ReversedStatus) ? "" : "disabled")><span class="glyphicon glyphicon-transfer mr5" aria-hidden="true"></span>红冲</button>
                                    <button id="btn_print" type="button" class="btn btn-alert ladda-button" data-style="zoom-out" value="打印" @((Model.Id > 0) ? "" : "disabled")>
                                        <i class="fa fa-floppy-o mr5"></i>打印
                                    </button>
                                    <button id="btn_cancel" type="button" class="btn btn-info ladda-button" data-style="zoom-out" @((Model.AuditedStatus || Model.ReversedStatus) ? "disabled" : "")><span class="glyphicon glyphicon-remove mr5" aria-hidden="true"></span>作废</button>
                                    <a class="btn btn-warning" href="@Context.Request.Query["returnURL"]"><i class="fa fa-undo mr5"></i> 返回</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </section>
    <!-- End: Content -->
</section>


@await Html.PartialAsync("_Windows", Model)

@{
//Html.AddCssFileParts(ResourceLocation.Head, "~/assets/skin/default_skin/css/theme.css");
//Html.AddCssFileParts(ResourceLocation.Head, "~/Scripts/Toastr/toastr.css");
//Html.AddCssFileParts(ResourceLocation.Head, "~/Scripts/Tables/bootstrap-table.css");
//Html.AddCssFileParts(ResourceLocation.Head, "~/vendor/plugins/datepicker/css/bootstrap-datetimepicker.css");
//Html.AddCssFileParts(ResourceLocation.Head, "~/vendor/plugins/daterange/daterangepicker.css");
//Html.AddCssFileParts(ResourceLocation.Head, "~/vendor/plugins/tagmanager/tagmanager.css");
//Html.AddCssFileParts(ResourceLocation.Head, "~/vendor/plugins/fancytree/skin-win8/ui.fancytree.min.css");
//Html.AddCssFileParts(ResourceLocation.Head, "~/Content/zTree.theme.metro.min.css");
//Html.AddCssFileParts(ResourceLocation.Head, "~/vendor/plugins/spin/spin.css");
//Html.AddCssFileParts(ResourceLocation.Head, "~/vendor/plugins/ladda/ladda.min.css");
}

@section NewDefinFrameWorkScripts
{
    @{
        Html.AddScriptParts(ResourceLocation.Footer, "~/vendor/jquery/jquery-1.11.1.min.js", order: 999);
        Html.AddScriptParts(ResourceLocation.Footer, "~/vendor/jquery/jquery_ui/jquery-ui.min.js", order: 999);
        Html.AddScriptParts(ResourceLocation.Footer, "~/assets/js/bootstrap/bootstrap.min.js", order: 999);
    }
}

@section CurPageScripts
{
    @{

//Html.AddScriptParts(ResourceLocation.Footer, "~/assets/js/utility/jquery.sparkline.min.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/Scripts/jquery.validate.min.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/Scripts/jquery.validate.unobtrusive.js");
////Html.AddScriptParts(ResourceLocation.Footer, "~/Scripts/Tables/jquery.treegrid.min.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/Scripts/jquery-ui-1.10.4.custom.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/Scripts/jquery.PrintArea.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/Scripts/Tables/bootstrap-table.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/Scripts/Tables/locale/bootstrap-table-zh-CN.min.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/Scripts/Tables/bootstrap-table-treeview.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/Scripts/globalize.min.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/Scripts/moment.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/Scripts/moment-with-locales.js");
////Html.AddScriptParts(ResourceLocation.Footer, "~/vendor/plugins/daterange/daterangepicker.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/vendor/plugins/datepicker/js/bootstrap-datetimepicker.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/vendor/plugins/jquerymask/jquery.maskedinput.min.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/vendor/plugins/tagmanager/tagmanager.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/vendor/plugins/fancytree/jquery.fancytree-all.min.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/Scripts/jquery.ztree.all-3.5.min.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/assets/js/bootstrap/holder.min.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/Scripts/Toastr/Toastr.min.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/Scripts/Custom/Common.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/vendor/plugins/spin/spin.js");
//Html.AddScriptParts(ResourceLocation.Footer, "~/vendor/plugins/ladda/ladda.min.js");

    }
    @await Html.PartialAsync("_Scripts", Model)
}

DCMS.Web/Views/ReturnReservationBill/_Toolbar.cshtml
    <div id="toolbar" class="btn-group mb10">
        <a href="@Url.Action("Create","ReturnReservationBill")"  class="btn btn-primary btn-sm mr5">
            <span class="glyphicon glyphicon-plus mr5"></span>添加
        </a>
        <div class="btn-group mr5">
            <button type="button" id="btn_export" class="btn btn-info btn-sm dropdown-toggle ladda-button" data-toggle="dropdown" aria-expanded="false">
                <span class="glyphicon glyphicon-print"></span>
                导出
                <span class="caret ml5"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
                <li>
                    <a id="export_select" href="#">导出选择</a>
                </li>
                <li>
                    <a id="export_all" href="#">导出全部</a>
                </li>
            </ul>
        </div>
        <div class="btn-group mr5">
            <button type="button" id="btn_print" class="btn btn-alert btn-sm dropdown-toggle ladda-button" data-toggle="dropdown" aria-expanded="false">
                <span class="glyphicon glyphicon-print"></span>
                打印
                <span class="caret ml5"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
                <li>
                    <a id="print_select" href="#">打印选择</a>
                </li>
                <li>
                    <a id="print_all" href="#">打印全部</a>
                </li>
            </ul>
        </div>
    </div>

DCMS.Web/Views/ReturnReservationBill/_Windows.cshtml
@{
    //客户选择
    await Html.RenderPartialAsync("_ModalForm", new ViewDataDictionary(ViewData) { { "formId", "TerminalSelectForm" }, { "modalWindow", "TerminalSelectModalWindow" }, { "windowWidth", "1000px" }, { "showSave", "true" } });
    //科目选择
    await Html.RenderPartialAsync("_ModalForm", new ViewDataDictionary(ViewData) { { "formId", "AccountingForm" }, { "modalWindow", "AccountingModalWindow" }, { "showSave", "true" } });
    //商品选择
    await Html.RenderPartialAsync("_ModalForm", new ViewDataDictionary(ViewData) { { "formId", "ProductModalForm" }, { "modalWindow", "ModalProductWindows" }, { "windowWidth", "1000px" }, { "showSave", "true" } });
}